/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useFrame } from 'react-three-fiber'
import { useGLTF } from '@react-three/drei/useGLTF'

import { useAnimations } from '@react-three/drei/useAnimations'

export default function Cat(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('../../../models/cat/source/cat.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          material={materials.palettemat}
          geometry={nodes.unamed.geometry}
          skeleton={nodes.unamed.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/cat/source/cat.glb')
