/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Qutiix (https://sketchfab.com/joshiisshh)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/c39ca7490aad4bc19e4f66816e8a7b34
title: Adventure Foxy FNAF WORLD
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'
import {useFrame} from 'react-three-fiber'

export default function Fox(props) {
  const { nodes, materials } = useGLTF('../../../models/foxy/fox.gltf')
  const ref = useRef();
  useFrame(()=>(ref.current.rotation.y +=0.01))
  return (
    <group ref={ref} {...props} dispose={null} position={[0,-33,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.material} geometry={nodes.mesh_0.geometry} />
        <mesh material={materials.Black} geometry={nodes.mesh_1.geometry} />
        <mesh material={materials.Black} geometry={nodes.mesh_2.geometry} />
        <mesh material={materials.Black} geometry={nodes.mesh_3.geometry} />
        <mesh material={materials.Orange_Skin} geometry={nodes.mesh_4.geometry} />
        <mesh material={materials.Orange_Skin} geometry={nodes.mesh_5.geometry} />
        <mesh material={materials.Pants} geometry={nodes.mesh_6.geometry} />
        <mesh material={materials.Pants} geometry={nodes.mesh_7.geometry} />
        <mesh material={materials.Pants} geometry={nodes.mesh_8.geometry} />
        <mesh material={materials.Red_skin} geometry={nodes.mesh_9.geometry} />
        <mesh material={materials.Red_skin} geometry={nodes.mesh_10.geometry} />
        <mesh material={materials.Red_skin} geometry={nodes.mesh_11.geometry} />
        <mesh material={materials.Red_skin} geometry={nodes.mesh_12.geometry} />
        <mesh material={materials.Red_skin} geometry={nodes.mesh_13.geometry} />
        <mesh material={materials.Teeth} geometry={nodes.mesh_14.geometry} />
        <mesh material={materials.metal} geometry={nodes.mesh_15.geometry} />
        <mesh material={materials.metal} geometry={nodes.mesh_16.geometry} />
        <mesh material={materials.metal} geometry={nodes.mesh_17.geometry} />
        <mesh material={materials.wire_008008136} geometry={nodes.mesh_18.geometry} />
        <mesh material={materials.wire_224086086} geometry={nodes.mesh_19.geometry} />
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/foxy/fox.gltf')
