/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'
import {useFrame} from 'react-three-fiber'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/source/model.gltf')

  const ref = useRef()
  useFrame(()=>(ref.current.rotation.y +=0.01))


  return (
    <group ref={ref} {...props} dispose={null} position={[0,-15,-0]}>
      <group position={[0, 5.5, 3.5]}>
        <group position={[0, 17.5, -30]}>
          <group position={[0, 0, -4]} rotation={[-0.17, 0, 0]}>
            <group rotation={[0.17, 0, 0]}>
              <group position={[0, -23, 30.5]}>
                <mesh material={nodes.mesh_13.material} geometry={nodes.mesh_13.geometry} />
                <mesh material={nodes.mesh_13_1.material} geometry={nodes.mesh_13_1.geometry} />
                <mesh material={nodes.mesh_13_2.material} geometry={nodes.mesh_13_2.geometry} />
                <mesh material={nodes.mesh_13_3.material} geometry={nodes.mesh_13_3.geometry} />
                <mesh material={nodes.mesh_13_4.material} geometry={nodes.mesh_13_4.geometry} />
                <mesh material={nodes.mesh_13_5.material} geometry={nodes.mesh_13_5.geometry} />
              </group>
              <group position={[6.5, 1, -9]}>
                <group position={[-6.5, -24, 39.5]}>
                  <mesh material={nodes.mesh_14.material} geometry={nodes.mesh_14.geometry} />
                  <mesh material={nodes.mesh_14_1.material} geometry={nodes.mesh_14_1.geometry} />
                  <mesh material={nodes.mesh_14_2.material} geometry={nodes.mesh_14_2.geometry} />
                  <mesh material={nodes.mesh_14_3.material} geometry={nodes.mesh_14_3.geometry} />
                  <mesh material={nodes.mesh_14_4.material} geometry={nodes.mesh_14_4.geometry} />
                  <mesh material={nodes.mesh_14_5.material} geometry={nodes.mesh_14_5.geometry} />
                  <mesh material={nodes.mesh_15.material} geometry={nodes.mesh_15.geometry} />
                  <mesh material={nodes.mesh_15_1.material} geometry={nodes.mesh_15_1.geometry} />
                  <mesh material={nodes.mesh_15_2.material} geometry={nodes.mesh_15_2.geometry} />
                  <mesh material={nodes.mesh_15_3.material} geometry={nodes.mesh_15_3.geometry} />
                  <mesh material={nodes.mesh_15_4.material} geometry={nodes.mesh_15_4.geometry} />
                  <mesh material={nodes.mesh_15_5.material} geometry={nodes.mesh_15_5.geometry} />
                </group>
              </group>
              <group position={[3, -6.5, -9]}>
                <group position={[-3, -16.5, 39.5]}>
                  <mesh material={nodes.mesh_16.material} geometry={nodes.mesh_16.geometry} />
                  <mesh material={nodes.mesh_16_1.material} geometry={nodes.mesh_16_1.geometry} />
                  <mesh material={nodes.mesh_16_2.material} geometry={nodes.mesh_16_2.geometry} />
                  <mesh material={nodes.mesh_16_3.material} geometry={nodes.mesh_16_3.geometry} />
                  <mesh material={nodes.mesh_16_4.material} geometry={nodes.mesh_16_4.geometry} />
                  <mesh material={nodes.mesh_16_5.material} geometry={nodes.mesh_16_5.geometry} />
                </group>
                <group position={[-3, -16.5, 39.5]}>
                  <mesh material={nodes.mesh_17.material} geometry={nodes.mesh_17.geometry} />
                  <mesh material={nodes.mesh_17_1.material} geometry={nodes.mesh_17_1.geometry} />
                  <mesh material={nodes.mesh_17_2.material} geometry={nodes.mesh_17_2.geometry} />
                  <mesh material={nodes.mesh_17_3.material} geometry={nodes.mesh_17_3.geometry} />
                  <mesh material={nodes.mesh_17_4.material} geometry={nodes.mesh_17_4.geometry} />
                  <mesh material={nodes.mesh_17_5.material} geometry={nodes.mesh_17_5.geometry} />
                </group>
                <group position={[-3, -16.5, 39.5]}>
                  <mesh material={nodes.mesh_18.material} geometry={nodes.mesh_18.geometry} />
                  <mesh material={nodes.mesh_18_1.material} geometry={nodes.mesh_18_1.geometry} />
                  <mesh material={nodes.mesh_18_2.material} geometry={nodes.mesh_18_2.geometry} />
                  <mesh material={nodes.mesh_18_3.material} geometry={nodes.mesh_18_3.geometry} />
                  <mesh material={nodes.mesh_18_4.material} geometry={nodes.mesh_18_4.geometry} />
                  <mesh material={nodes.mesh_18_5.material} geometry={nodes.mesh_18_5.geometry} />
                </group>
              </group>
              <group position={[-3, -6.5, -9]}>
                <group position={[3, -16.5, 39.5]}>
                  <mesh material={nodes.mesh_19.material} geometry={nodes.mesh_19.geometry} />
                  <mesh material={nodes.mesh_19_1.material} geometry={nodes.mesh_19_1.geometry} />
                  <mesh material={nodes.mesh_19_2.material} geometry={nodes.mesh_19_2.geometry} />
                  <mesh material={nodes.mesh_19_3.material} geometry={nodes.mesh_19_3.geometry} />
                  <mesh material={nodes.mesh_19_4.material} geometry={nodes.mesh_19_4.geometry} />
                  <mesh material={nodes.mesh_19_5.material} geometry={nodes.mesh_19_5.geometry} />
                  <mesh material={nodes.mesh_20.material} geometry={nodes.mesh_20.geometry} />
                  <mesh material={nodes.mesh_20_1.material} geometry={nodes.mesh_20_1.geometry} />
                  <mesh material={nodes.mesh_20_2.material} geometry={nodes.mesh_20_2.geometry} />
                  <mesh material={nodes.mesh_20_3.material} geometry={nodes.mesh_20_3.geometry} />
                  <mesh material={nodes.mesh_20_4.material} geometry={nodes.mesh_20_4.geometry} />
                  <mesh material={nodes.mesh_20_5.material} geometry={nodes.mesh_20_5.geometry} />
                  <mesh material={nodes.mesh_21.material} geometry={nodes.mesh_21.geometry} />
                  <mesh material={nodes.mesh_21_1.material} geometry={nodes.mesh_21_1.geometry} />
                  <mesh material={nodes.mesh_21_2.material} geometry={nodes.mesh_21_2.geometry} />
                  <mesh material={nodes.mesh_21_3.material} geometry={nodes.mesh_21_3.geometry} />
                  <mesh material={nodes.mesh_21_4.material} geometry={nodes.mesh_21_4.geometry} />
                  <mesh material={nodes.mesh_21_5.material} geometry={nodes.mesh_21_5.geometry} />
                </group>
              </group>
              <group position={[-6.5, 1, -9]}>
                <group position={[6.5, -24, 39.5]}>
                  <mesh material={nodes.mesh_22.material} geometry={nodes.mesh_22.geometry} />
                  <mesh material={nodes.mesh_22_1.material} geometry={nodes.mesh_22_1.geometry} />
                  <mesh material={nodes.mesh_22_2.material} geometry={nodes.mesh_22_2.geometry} />
                  <mesh material={nodes.mesh_22_3.material} geometry={nodes.mesh_22_3.geometry} />
                  <mesh material={nodes.mesh_22_4.material} geometry={nodes.mesh_22_4.geometry} />
                  <mesh material={nodes.mesh_22_5.material} geometry={nodes.mesh_22_5.geometry} />
                </group>
                <group position={[6.5, -24, 39.5]}>
                  <mesh material={nodes.mesh_23.material} geometry={nodes.mesh_23.geometry} />
                  <mesh material={nodes.mesh_23_1.material} geometry={nodes.mesh_23_1.geometry} />
                  <mesh material={nodes.mesh_23_2.material} geometry={nodes.mesh_23_2.geometry} />
                  <mesh material={nodes.mesh_23_3.material} geometry={nodes.mesh_23_3.geometry} />
                  <mesh material={nodes.mesh_23_4.material} geometry={nodes.mesh_23_4.geometry} />
                  <mesh material={nodes.mesh_23_5.material} geometry={nodes.mesh_23_5.geometry} />
                </group>
              </group>
              <group position={[0, 2.86, -12.03]} rotation={[Math.PI / 6, 0, 0]}>
                <group position={[0, -3, 0]} rotation={[-1.13, 0, 0]}>
                  <group position={[0, -22.86, 42.53]}>
                    <mesh material={nodes.mesh_25.material} geometry={nodes.mesh_25.geometry} />
                    <mesh material={nodes.mesh_25_1.material} geometry={nodes.mesh_25_1.geometry} />
                    <mesh material={nodes.mesh_25_2.material} geometry={nodes.mesh_25_2.geometry} />
                    <mesh material={nodes.mesh_25_3.material} geometry={nodes.mesh_25_3.geometry} />
                    <mesh material={nodes.mesh_25_4.material} geometry={nodes.mesh_25_4.geometry} />
                    <mesh material={nodes.mesh_25_5.material} geometry={nodes.mesh_25_5.geometry} />
                  </group>
                </group>
                <group position={[0, -25.86, 42.53]}>
                  <mesh material={nodes.mesh_24.material} geometry={nodes.mesh_24.geometry} />
                  <mesh material={nodes.mesh_24_1.material} geometry={nodes.mesh_24_1.geometry} />
                  <mesh material={nodes.mesh_24_2.material} geometry={nodes.mesh_24_2.geometry} />
                  <mesh material={nodes.mesh_24_3.material} geometry={nodes.mesh_24_3.geometry} />
                  <mesh material={nodes.mesh_24_4.material} geometry={nodes.mesh_24_4.geometry} />
                  <mesh material={nodes.mesh_24_5.material} geometry={nodes.mesh_24_5.geometry} />
                </group>
              </group>
              <group position={[-4.9, -8.14, -8.03]} rotation={[-0.61, 0, 0]}>
                <group position={[4.9, -14.86, 38.53]}>
                  <mesh material={nodes.mesh_27.material} geometry={nodes.mesh_27.geometry} />
                  <mesh material={nodes.mesh_27_1.material} geometry={nodes.mesh_27_1.geometry} />
                  <mesh material={nodes.mesh_27_2.material} geometry={nodes.mesh_27_2.geometry} />
                  <mesh material={nodes.mesh_27_3.material} geometry={nodes.mesh_27_3.geometry} />
                  <mesh material={nodes.mesh_27_4.material} geometry={nodes.mesh_27_4.geometry} />
                  <mesh material={nodes.mesh_27_5.material} geometry={nodes.mesh_27_5.geometry} />
                </group>
                <group position={[4.9, -14.86, 38.53]}>
                  <mesh material={nodes.mesh_26.material} geometry={nodes.mesh_26.geometry} />
                  <mesh material={nodes.mesh_26_1.material} geometry={nodes.mesh_26_1.geometry} />
                  <mesh material={nodes.mesh_26_2.material} geometry={nodes.mesh_26_2.geometry} />
                  <mesh material={nodes.mesh_26_3.material} geometry={nodes.mesh_26_3.geometry} />
                  <mesh material={nodes.mesh_26_4.material} geometry={nodes.mesh_26_4.geometry} />
                  <mesh material={nodes.mesh_26_5.material} geometry={nodes.mesh_26_5.geometry} />
                </group>
              </group>
              <group position={[0, -23, 30.5]}>
                <mesh material={nodes.mesh_7.material} geometry={nodes.mesh_7.geometry} />
                <mesh material={nodes.mesh_7_1.material} geometry={nodes.mesh_7_1.geometry} />
                <mesh material={nodes.mesh_7_2.material} geometry={nodes.mesh_7_2.geometry} />
                <mesh material={nodes.mesh_7_3.material} geometry={nodes.mesh_7_3.geometry} />
                <mesh material={nodes.mesh_7_4.material} geometry={nodes.mesh_7_4.geometry} />
                <mesh material={nodes.mesh_7_5.material} geometry={nodes.mesh_7_5.geometry} />
              </group>
              <group position={[0, -23, 30.5]}>
                <mesh material={nodes.mesh_8.material} geometry={nodes.mesh_8.geometry} />
                <mesh material={nodes.mesh_8_1.material} geometry={nodes.mesh_8_1.geometry} />
                <mesh material={nodes.mesh_8_2.material} geometry={nodes.mesh_8_2.geometry} />
                <mesh material={nodes.mesh_8_3.material} geometry={nodes.mesh_8_3.geometry} />
                <mesh material={nodes.mesh_8_4.material} geometry={nodes.mesh_8_4.geometry} />
                <mesh material={nodes.mesh_8_5.material} geometry={nodes.mesh_8_5.geometry} />
              </group>
              <group position={[0, -23, 30.5]}>
                <mesh material={nodes.mesh_9.material} geometry={nodes.mesh_9.geometry} />
                <mesh material={nodes.mesh_9_1.material} geometry={nodes.mesh_9_1.geometry} />
                <mesh material={nodes.mesh_9_2.material} geometry={nodes.mesh_9_2.geometry} />
                <mesh material={nodes.mesh_9_3.material} geometry={nodes.mesh_9_3.geometry} />
                <mesh material={nodes.mesh_9_4.material} geometry={nodes.mesh_9_4.geometry} />
                <mesh material={nodes.mesh_9_5.material} geometry={nodes.mesh_9_5.geometry} />
              </group>
              <group position={[0, -23, 30.5]}>
                <mesh material={nodes.mesh_10.material} geometry={nodes.mesh_10.geometry} />
                <mesh material={nodes.mesh_10_1.material} geometry={nodes.mesh_10_1.geometry} />
                <mesh material={nodes.mesh_10_2.material} geometry={nodes.mesh_10_2.geometry} />
                <mesh material={nodes.mesh_10_3.material} geometry={nodes.mesh_10_3.geometry} />
                <mesh material={nodes.mesh_10_4.material} geometry={nodes.mesh_10_4.geometry} />
                <mesh material={nodes.mesh_10_5.material} geometry={nodes.mesh_10_5.geometry} />
              </group>
              <group position={[0, -23, 30.5]}>
                <mesh material={nodes.mesh_11.material} geometry={nodes.mesh_11.geometry} />
                <mesh material={nodes.mesh_11_1.material} geometry={nodes.mesh_11_1.geometry} />
                <mesh material={nodes.mesh_11_2.material} geometry={nodes.mesh_11_2.geometry} />
                <mesh material={nodes.mesh_11_3.material} geometry={nodes.mesh_11_3.geometry} />
                <mesh material={nodes.mesh_11_4.material} geometry={nodes.mesh_11_4.geometry} />
                <mesh material={nodes.mesh_11_5.material} geometry={nodes.mesh_11_5.geometry} />
              </group>
              <group position={[0, -23, 30.5]}>
                <mesh material={nodes.mesh_12.material} geometry={nodes.mesh_12.geometry} />
                <mesh material={nodes.mesh_12_1.material} geometry={nodes.mesh_12_1.geometry} />
                <mesh material={nodes.mesh_12_2.material} geometry={nodes.mesh_12_2.geometry} />
                <mesh material={nodes.mesh_12_3.material} geometry={nodes.mesh_12_3.geometry} />
                <mesh material={nodes.mesh_12_4.material} geometry={nodes.mesh_12_4.geometry} />
                <mesh material={nodes.mesh_12_5.material} geometry={nodes.mesh_12_5.geometry} />
              </group>
            </group>
            <group position={[0, -23, 30.5]}>
              <mesh material={nodes.mesh_6.material} geometry={nodes.mesh_6.geometry} />
              <mesh material={nodes.mesh_6_1.material} geometry={nodes.mesh_6_1.geometry} />
              <mesh material={nodes.mesh_6_2.material} geometry={nodes.mesh_6_2.geometry} />
              <mesh material={nodes.mesh_6_3.material} geometry={nodes.mesh_6_3.geometry} />
              <mesh material={nodes.mesh_6_4.material} geometry={nodes.mesh_6_4.geometry} />
              <mesh material={nodes.mesh_6_5.material} geometry={nodes.mesh_6_5.geometry} />
            </group>
          </group>
          <group position={[0, -23, 26.5]}>
            <mesh material={nodes.mesh_5.material} geometry={nodes.mesh_5.geometry} />
            <mesh material={nodes.mesh_5_1.material} geometry={nodes.mesh_5_1.geometry} />
            <mesh material={nodes.mesh_5_2.material} geometry={nodes.mesh_5_2.geometry} />
            <mesh material={nodes.mesh_5_3.material} geometry={nodes.mesh_5_3.geometry} />
            <mesh material={nodes.mesh_5_4.material} geometry={nodes.mesh_5_4.geometry} />
            <mesh material={nodes.mesh_5_5.material} geometry={nodes.mesh_5_5.geometry} />
          </group>
        </group>
        <group position={[0, 28.5, -30]} rotation={[-0.26, 0, 0]}>
          <group position={[0, -34, 26.5]}>
            <mesh material={nodes.mesh_28.material} geometry={nodes.mesh_28.geometry} />
            <mesh material={nodes.mesh_28_1.material} geometry={nodes.mesh_28_1.geometry} />
            <mesh material={nodes.mesh_28_2.material} geometry={nodes.mesh_28_2.geometry} />
            <mesh material={nodes.mesh_28_3.material} geometry={nodes.mesh_28_3.geometry} />
            <mesh material={nodes.mesh_28_4.material} geometry={nodes.mesh_28_4.geometry} />
            <mesh material={nodes.mesh_28_5.material} geometry={nodes.mesh_28_5.geometry} />
          </group>
        </group>
        <group position={[0, 28.5, 14]} rotation={[0.26, 0, 0]}>
          <group position={[0, -34, -17.5]}>
            <mesh material={nodes.mesh_29.material} geometry={nodes.mesh_29.geometry} />
            <mesh material={nodes.mesh_29_1.material} geometry={nodes.mesh_29_1.geometry} />
            <mesh material={nodes.mesh_29_2.material} geometry={nodes.mesh_29_2.geometry} />
            <mesh material={nodes.mesh_29_3.material} geometry={nodes.mesh_29_3.geometry} />
            <mesh material={nodes.mesh_29_4.material} geometry={nodes.mesh_29_4.geometry} />
            <mesh material={nodes.mesh_29_5.material} geometry={nodes.mesh_29_5.geometry} />
          </group>
        </group>
        <group position={[12, 13.5, -7.5]} rotation={[0, 0, 0.1]}>
          <group position={[-12, -19, 4]}>
            <mesh material={nodes.mesh_30.material} geometry={nodes.mesh_30.geometry} />
            <mesh material={nodes.mesh_30_1.material} geometry={nodes.mesh_30_1.geometry} />
            <mesh material={nodes.mesh_30_2.material} geometry={nodes.mesh_30_2.geometry} />
            <mesh material={nodes.mesh_30_3.material} geometry={nodes.mesh_30_3.geometry} />
            <mesh material={nodes.mesh_30_4.material} geometry={nodes.mesh_30_4.geometry} />
            <mesh material={nodes.mesh_30_5.material} geometry={nodes.mesh_30_5.geometry} />
          </group>
        </group>
        <group position={[11, 13.5, -22.5]} rotation={[0, 0, 0.14]}>
          <group position={[-11, -19, 19]}>
            <mesh material={nodes.mesh_31.material} geometry={nodes.mesh_31.geometry} />
            <mesh material={nodes.mesh_31_1.material} geometry={nodes.mesh_31_1.geometry} />
            <mesh material={nodes.mesh_31_2.material} geometry={nodes.mesh_31_2.geometry} />
            <mesh material={nodes.mesh_31_3.material} geometry={nodes.mesh_31_3.geometry} />
            <mesh material={nodes.mesh_31_4.material} geometry={nodes.mesh_31_4.geometry} />
            <mesh material={nodes.mesh_31_5.material} geometry={nodes.mesh_31_5.geometry} />
          </group>
          <group position={[-11, -19, 19]}>
            <mesh material={nodes.mesh_32.material} geometry={nodes.mesh_32.geometry} />
            <mesh material={nodes.mesh_32_1.material} geometry={nodes.mesh_32_1.geometry} />
            <mesh material={nodes.mesh_32_2.material} geometry={nodes.mesh_32_2.geometry} />
            <mesh material={nodes.mesh_32_3.material} geometry={nodes.mesh_32_3.geometry} />
            <mesh material={nodes.mesh_32_4.material} geometry={nodes.mesh_32_4.geometry} />
            <mesh material={nodes.mesh_32_5.material} geometry={nodes.mesh_32_5.geometry} />
          </group>
        </group>
        <group position={[-11, 13.5, -22.5]} rotation={[0, 0, -0.14]}>
          <group position={[11, -19, 19]}>
            <mesh material={nodes.mesh_33.material} geometry={nodes.mesh_33.geometry} />
            <mesh material={nodes.mesh_33_1.material} geometry={nodes.mesh_33_1.geometry} />
            <mesh material={nodes.mesh_33_2.material} geometry={nodes.mesh_33_2.geometry} />
            <mesh material={nodes.mesh_33_3.material} geometry={nodes.mesh_33_3.geometry} />
            <mesh material={nodes.mesh_33_4.material} geometry={nodes.mesh_33_4.geometry} />
            <mesh material={nodes.mesh_33_5.material} geometry={nodes.mesh_33_5.geometry} />
          </group>
          <group position={[11, -19, 19]}>
            <mesh material={nodes.mesh_34.material} geometry={nodes.mesh_34.geometry} />
            <mesh material={nodes.mesh_34_1.material} geometry={nodes.mesh_34_1.geometry} />
            <mesh material={nodes.mesh_34_2.material} geometry={nodes.mesh_34_2.geometry} />
            <mesh material={nodes.mesh_34_3.material} geometry={nodes.mesh_34_3.geometry} />
            <mesh material={nodes.mesh_34_4.material} geometry={nodes.mesh_34_4.geometry} />
            <mesh material={nodes.mesh_34_5.material} geometry={nodes.mesh_34_5.geometry} />
          </group>
        </group>
        <group position={[-12, 13.5, -8]} rotation={[0, 0, -0.1]}>
          <group position={[12, -19, 4.5]}>
            <mesh material={nodes.mesh_35.material} geometry={nodes.mesh_35.geometry} />
            <mesh material={nodes.mesh_35_1.material} geometry={nodes.mesh_35_1.geometry} />
            <mesh material={nodes.mesh_35_2.material} geometry={nodes.mesh_35_2.geometry} />
            <mesh material={nodes.mesh_35_3.material} geometry={nodes.mesh_35_3.geometry} />
            <mesh material={nodes.mesh_35_4.material} geometry={nodes.mesh_35_4.geometry} />
            <mesh material={nodes.mesh_35_5.material} geometry={nodes.mesh_35_5.geometry} />
          </group>
        </group>
        <group position={[12, 13.5, -8]} rotation={[0, 0, -Math.PI / 9]}>
          <group position={[-12, -19, 4.5]}>
            <mesh material={nodes.mesh_36.material} geometry={nodes.mesh_36.geometry} />
            <mesh material={nodes.mesh_36_1.material} geometry={nodes.mesh_36_1.geometry} />
            <mesh material={nodes.mesh_36_2.material} geometry={nodes.mesh_36_2.geometry} />
            <mesh material={nodes.mesh_36_3.material} geometry={nodes.mesh_36_3.geometry} />
            <mesh material={nodes.mesh_36_4.material} geometry={nodes.mesh_36_4.geometry} />
            <mesh material={nodes.mesh_36_5.material} geometry={nodes.mesh_36_5.geometry} />
            <mesh material={nodes.mesh_37.material} geometry={nodes.mesh_37.geometry} />
            <mesh material={nodes.mesh_37_1.material} geometry={nodes.mesh_37_1.geometry} />
            <mesh material={nodes.mesh_37_2.material} geometry={nodes.mesh_37_2.geometry} />
            <mesh material={nodes.mesh_37_3.material} geometry={nodes.mesh_37_3.geometry} />
            <mesh material={nodes.mesh_37_4.material} geometry={nodes.mesh_37_4.geometry} />
            <mesh material={nodes.mesh_37_5.material} geometry={nodes.mesh_37_5.geometry} />
          </group>
        </group>
        <group position={[-12, 13.5, -8]} rotation={[0, 0, Math.PI / 9]}>
          <group position={[12, -19, 4.5]}>
            <mesh material={nodes.mesh_38.material} geometry={nodes.mesh_38.geometry} />
            <mesh material={nodes.mesh_38_1.material} geometry={nodes.mesh_38_1.geometry} />
            <mesh material={nodes.mesh_38_2.material} geometry={nodes.mesh_38_2.geometry} />
            <mesh material={nodes.mesh_38_3.material} geometry={nodes.mesh_38_3.geometry} />
            <mesh material={nodes.mesh_38_4.material} geometry={nodes.mesh_38_4.geometry} />
            <mesh material={nodes.mesh_38_5.material} geometry={nodes.mesh_38_5.geometry} />
          </group>
          <group position={[12, -19, 4.5]}>
            <mesh material={nodes.mesh_39.material} geometry={nodes.mesh_39.geometry} />
            <mesh material={nodes.mesh_39_1.material} geometry={nodes.mesh_39_1.geometry} />
            <mesh material={nodes.mesh_39_2.material} geometry={nodes.mesh_39_2.geometry} />
            <mesh material={nodes.mesh_39_3.material} geometry={nodes.mesh_39_3.geometry} />
            <mesh material={nodes.mesh_39_4.material} geometry={nodes.mesh_39_4.geometry} />
            <mesh material={nodes.mesh_39_5.material} geometry={nodes.mesh_39_5.geometry} />
          </group>
        </group>
        <group position={[5.5, 9.75, -14]}>
          <group position={[3.5, 0.25, -8]}>
            <group position={[-9, -15.5, 18.5]}>
              <mesh material={nodes.mesh_40.material} geometry={nodes.mesh_40.geometry} />
              <mesh material={nodes.mesh_40_1.material} geometry={nodes.mesh_40_1.geometry} />
              <mesh material={nodes.mesh_40_2.material} geometry={nodes.mesh_40_2.geometry} />
              <mesh material={nodes.mesh_40_3.material} geometry={nodes.mesh_40_3.geometry} />
              <mesh material={nodes.mesh_40_4.material} geometry={nodes.mesh_40_4.geometry} />
              <mesh material={nodes.mesh_40_5.material} geometry={nodes.mesh_40_5.geometry} />
            </group>
            <group position={[-9, -15.5, 18.5]}>
              <mesh material={nodes.mesh_41.material} geometry={nodes.mesh_41.geometry} />
              <mesh material={nodes.mesh_41_1.material} geometry={nodes.mesh_41_1.geometry} />
              <mesh material={nodes.mesh_41_2.material} geometry={nodes.mesh_41_2.geometry} />
              <mesh material={nodes.mesh_41_3.material} geometry={nodes.mesh_41_3.geometry} />
              <mesh material={nodes.mesh_41_4.material} geometry={nodes.mesh_41_4.geometry} />
              <mesh material={nodes.mesh_41_5.material} geometry={nodes.mesh_41_5.geometry} />
            </group>
            <group position={[-1, -0.25, 0]}>
              <group position={[-8, -15.25, 18.5]}>
                <mesh material={nodes.mesh_42.material} geometry={nodes.mesh_42.geometry} />
                <mesh material={nodes.mesh_42_1.material} geometry={nodes.mesh_42_1.geometry} />
                <mesh material={nodes.mesh_42_2.material} geometry={nodes.mesh_42_2.geometry} />
                <mesh material={nodes.mesh_42_3.material} geometry={nodes.mesh_42_3.geometry} />
                <mesh material={nodes.mesh_42_4.material} geometry={nodes.mesh_42_4.geometry} />
                <mesh material={nodes.mesh_42_5.material} geometry={nodes.mesh_42_5.geometry} />
              </group>
              <group position={[0.5, -14, 0]}>
                <group position={[-8.5, -1.25, 18.5]}>
                  <mesh material={nodes.mesh_43.material} geometry={nodes.mesh_43.geometry} />
                  <mesh material={nodes.mesh_43_1.material} geometry={nodes.mesh_43_1.geometry} />
                  <mesh material={nodes.mesh_43_2.material} geometry={nodes.mesh_43_2.geometry} />
                  <mesh material={nodes.mesh_43_3.material} geometry={nodes.mesh_43_3.geometry} />
                  <mesh material={nodes.mesh_43_4.material} geometry={nodes.mesh_43_4.geometry} />
                  <mesh material={nodes.mesh_43_5.material} geometry={nodes.mesh_43_5.geometry} />
                </group>
                <group position={[0.5, 0, 0]}>
                  <group position={[-9, -1.25, 18.5]}>
                    <mesh material={nodes.mesh_44.material} geometry={nodes.mesh_44.geometry} />
                    <mesh material={nodes.mesh_44_1.material} geometry={nodes.mesh_44_1.geometry} />
                    <mesh material={nodes.mesh_44_2.material} geometry={nodes.mesh_44_2.geometry} />
                    <mesh material={nodes.mesh_44_3.material} geometry={nodes.mesh_44_3.geometry} />
                    <mesh material={nodes.mesh_44_4.material} geometry={nodes.mesh_44_4.geometry} />
                    <mesh material={nodes.mesh_44_5.material} geometry={nodes.mesh_44_5.geometry} />
                  </group>
                  <group position={[0, -18.25, 0]}>
                    <group position={[-9, 17, 18.5]}>
                      <mesh material={nodes.mesh_45.material} geometry={nodes.mesh_45.geometry} />
                      <mesh material={nodes.mesh_45_1.material} geometry={nodes.mesh_45_1.geometry} />
                      <mesh material={nodes.mesh_45_2.material} geometry={nodes.mesh_45_2.geometry} />
                      <mesh material={nodes.mesh_45_3.material} geometry={nodes.mesh_45_3.geometry} />
                      <mesh material={nodes.mesh_45_4.material} geometry={nodes.mesh_45_4.geometry} />
                      <mesh material={nodes.mesh_45_5.material} geometry={nodes.mesh_45_5.geometry} />
                    </group>
                    <group position={[-9, 17, 18.5]}>
                      <mesh material={nodes.mesh_46.material} geometry={nodes.mesh_46.geometry} />
                      <mesh material={nodes.mesh_46_1.material} geometry={nodes.mesh_46_1.geometry} />
                      <mesh material={nodes.mesh_46_2.material} geometry={nodes.mesh_46_2.geometry} />
                      <mesh material={nodes.mesh_46_3.material} geometry={nodes.mesh_46_3.geometry} />
                      <mesh material={nodes.mesh_46_4.material} geometry={nodes.mesh_46_4.geometry} />
                      <mesh material={nodes.mesh_46_5.material} geometry={nodes.mesh_46_5.geometry} />
                    </group>
                    <group position={[-9, 17, 18.5]}>
                      <mesh material={nodes.mesh_47.material} geometry={nodes.mesh_47.geometry} />
                      <mesh material={nodes.mesh_47_1.material} geometry={nodes.mesh_47_1.geometry} />
                      <mesh material={nodes.mesh_47_2.material} geometry={nodes.mesh_47_2.geometry} />
                      <mesh material={nodes.mesh_47_3.material} geometry={nodes.mesh_47_3.geometry} />
                      <mesh material={nodes.mesh_47_4.material} geometry={nodes.mesh_47_4.geometry} />
                      <mesh material={nodes.mesh_47_5.material} geometry={nodes.mesh_47_5.geometry} />
                    </group>
                    <group position={[-9, 17, 18.5]}>
                      <mesh material={nodes.mesh_48.material} geometry={nodes.mesh_48.geometry} />
                      <mesh material={nodes.mesh_48_1.material} geometry={nodes.mesh_48_1.geometry} />
                      <mesh material={nodes.mesh_48_2.material} geometry={nodes.mesh_48_2.geometry} />
                      <mesh material={nodes.mesh_48_3.material} geometry={nodes.mesh_48_3.geometry} />
                      <mesh material={nodes.mesh_48_4.material} geometry={nodes.mesh_48_4.geometry} />
                      <mesh material={nodes.mesh_48_5.material} geometry={nodes.mesh_48_5.geometry} />
                    </group>
                    <group position={[0, 3.25, -5]} rotation={[-Math.PI / 4, 0, 0]}>
                      <group position={[-9, 13.75, 23.5]}>
                        <mesh material={nodes.mesh_49.material} geometry={nodes.mesh_49.geometry} />
                        <mesh material={nodes.mesh_49_1.material} geometry={nodes.mesh_49_1.geometry} />
                        <mesh material={nodes.mesh_49_2.material} geometry={nodes.mesh_49_2.geometry} />
                        <mesh material={nodes.mesh_49_3.material} geometry={nodes.mesh_49_3.geometry} />
                        <mesh material={nodes.mesh_49_4.material} geometry={nodes.mesh_49_4.geometry} />
                        <mesh material={nodes.mesh_49_5.material} geometry={nodes.mesh_49_5.geometry} />
                      </group>
                    </group>
                    <group position={[0, 3.25, 5]} rotation={[-2.36, 0, 0]}>
                      <group position={[-9, 13.75, 13.5]}>
                        <mesh material={nodes.mesh_50.material} geometry={nodes.mesh_50.geometry} />
                        <mesh material={nodes.mesh_50_1.material} geometry={nodes.mesh_50_1.geometry} />
                        <mesh material={nodes.mesh_50_2.material} geometry={nodes.mesh_50_2.geometry} />
                        <mesh material={nodes.mesh_50_3.material} geometry={nodes.mesh_50_3.geometry} />
                        <mesh material={nodes.mesh_50_4.material} geometry={nodes.mesh_50_4.geometry} />
                        <mesh material={nodes.mesh_50_5.material} geometry={nodes.mesh_50_5.geometry} />
                      </group>
                    </group>
                    <group position={[-0.5, 1.75, 0]}>
                      <group position={[-8.5, 15.25, 18.5]}>
                        <mesh material={nodes.mesh_51.material} geometry={nodes.mesh_51.geometry} />
                        <mesh material={nodes.mesh_51_1.material} geometry={nodes.mesh_51_1.geometry} />
                        <mesh material={nodes.mesh_51_2.material} geometry={nodes.mesh_51_2.geometry} />
                        <mesh material={nodes.mesh_51_3.material} geometry={nodes.mesh_51_3.geometry} />
                        <mesh material={nodes.mesh_51_4.material} geometry={nodes.mesh_51_4.geometry} />
                        <mesh material={nodes.mesh_51_5.material} geometry={nodes.mesh_51_5.geometry} />
                      </group>
                      <group position={[-8.5, 15.25, 18.5]}>
                        <mesh material={nodes.mesh_52.material} geometry={nodes.mesh_52.geometry} />
                        <mesh material={nodes.mesh_52_1.material} geometry={nodes.mesh_52_1.geometry} />
                        <mesh material={nodes.mesh_52_2.material} geometry={nodes.mesh_52_2.geometry} />
                        <mesh material={nodes.mesh_52_3.material} geometry={nodes.mesh_52_3.geometry} />
                        <mesh material={nodes.mesh_52_4.material} geometry={nodes.mesh_52_4.geometry} />
                        <mesh material={nodes.mesh_52_5.material} geometry={nodes.mesh_52_5.geometry} />
                      </group>
                      <group position={[-8.5, 15.25, 18.5]}>
                        <mesh material={nodes.mesh_53.material} geometry={nodes.mesh_53.geometry} />
                        <mesh material={nodes.mesh_53_1.material} geometry={nodes.mesh_53_1.geometry} />
                        <mesh material={nodes.mesh_53_2.material} geometry={nodes.mesh_53_2.geometry} />
                        <mesh material={nodes.mesh_53_3.material} geometry={nodes.mesh_53_3.geometry} />
                        <mesh material={nodes.mesh_53_4.material} geometry={nodes.mesh_53_4.geometry} />
                        <mesh material={nodes.mesh_53_5.material} geometry={nodes.mesh_53_5.geometry} />
                      </group>
                      <group position={[-8.5, 15.25, 18.5]}>
                        <mesh material={nodes.mesh_54.material} geometry={nodes.mesh_54.geometry} />
                        <mesh material={nodes.mesh_54_1.material} geometry={nodes.mesh_54_1.geometry} />
                        <mesh material={nodes.mesh_54_2.material} geometry={nodes.mesh_54_2.geometry} />
                        <mesh material={nodes.mesh_54_3.material} geometry={nodes.mesh_54_3.geometry} />
                        <mesh material={nodes.mesh_54_4.material} geometry={nodes.mesh_54_4.geometry} />
                        <mesh material={nodes.mesh_54_5.material} geometry={nodes.mesh_54_5.geometry} />
                      </group>
                      <group position={[0.5, -3.25, -5]} rotation={[-0.17, 0, 0]}>
                        <group position={[-9, 18.5, 23.5]}>
                          <mesh material={nodes.mesh_55.material} geometry={nodes.mesh_55.geometry} />
                          <mesh material={nodes.mesh_55_1.material} geometry={nodes.mesh_55_1.geometry} />
                          <mesh material={nodes.mesh_55_2.material} geometry={nodes.mesh_55_2.geometry} />
                          <mesh material={nodes.mesh_55_3.material} geometry={nodes.mesh_55_3.geometry} />
                          <mesh material={nodes.mesh_55_4.material} geometry={nodes.mesh_55_4.geometry} />
                          <mesh material={nodes.mesh_55_5.material} geometry={nodes.mesh_55_5.geometry} />
                        </group>
                      </group>
                      <group position={[0.5, -3.25, 5]} rotation={[0.17, 0, 0]}>
                        <group position={[-9, 18.5, 13.5]}>
                          <mesh material={nodes.mesh_56.material} geometry={nodes.mesh_56.geometry} />
                          <mesh material={nodes.mesh_56_1.material} geometry={nodes.mesh_56_1.geometry} />
                          <mesh material={nodes.mesh_56_2.material} geometry={nodes.mesh_56_2.geometry} />
                          <mesh material={nodes.mesh_56_3.material} geometry={nodes.mesh_56_3.geometry} />
                          <mesh material={nodes.mesh_56_4.material} geometry={nodes.mesh_56_4.geometry} />
                          <mesh material={nodes.mesh_56_5.material} geometry={nodes.mesh_56_5.geometry} />
                        </group>
                      </group>
                      <group position={[5.5, -3.25, 0]} rotation={[Math.PI / 2, 1.4, -Math.PI / 2]}>
                        <group position={[-14, 18.5, 18.5]}>
                          <mesh material={nodes.mesh_57.material} geometry={nodes.mesh_57.geometry} />
                          <mesh material={nodes.mesh_57_1.material} geometry={nodes.mesh_57_1.geometry} />
                          <mesh material={nodes.mesh_57_2.material} geometry={nodes.mesh_57_2.geometry} />
                          <mesh material={nodes.mesh_57_3.material} geometry={nodes.mesh_57_3.geometry} />
                          <mesh material={nodes.mesh_57_4.material} geometry={nodes.mesh_57_4.geometry} />
                          <mesh material={nodes.mesh_57_5.material} geometry={nodes.mesh_57_5.geometry} />
                        </group>
                      </group>
                      <group position={[-4.5, -3.25, 0]} rotation={[-Math.PI / 2, 1.4, Math.PI / 2]}>
                        <group position={[-4, 18.5, 18.5]}>
                          <mesh material={nodes.mesh_58.material} geometry={nodes.mesh_58.geometry} />
                          <mesh material={nodes.mesh_58_1.material} geometry={nodes.mesh_58_1.geometry} />
                          <mesh material={nodes.mesh_58_2.material} geometry={nodes.mesh_58_2.geometry} />
                          <mesh material={nodes.mesh_58_3.material} geometry={nodes.mesh_58_3.geometry} />
                          <mesh material={nodes.mesh_58_4.material} geometry={nodes.mesh_58_4.geometry} />
                          <mesh material={nodes.mesh_58_5.material} geometry={nodes.mesh_58_5.geometry} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group position={[5.5, 9.75, -2]}>
          <group position={[-5.5, -15.25, -1.5]}>
            <mesh material={nodes.mesh_59.material} geometry={nodes.mesh_59.geometry} />
            <mesh material={nodes.mesh_59_1.material} geometry={nodes.mesh_59_1.geometry} />
            <mesh material={nodes.mesh_59_2.material} geometry={nodes.mesh_59_2.geometry} />
            <mesh material={nodes.mesh_59_3.material} geometry={nodes.mesh_59_3.geometry} />
            <mesh material={nodes.mesh_59_4.material} geometry={nodes.mesh_59_4.geometry} />
            <mesh material={nodes.mesh_59_5.material} geometry={nodes.mesh_59_5.geometry} />
            <group position={[9, 15.5, 9.5]}>
              <group position={[-9, -15.5, -9.5]}>
                <mesh material={nodes.mesh_60.material} geometry={nodes.mesh_60.geometry} />
                <mesh material={nodes.mesh_60_1.material} geometry={nodes.mesh_60_1.geometry} />
                <mesh material={nodes.mesh_60_2.material} geometry={nodes.mesh_60_2.geometry} />
                <mesh material={nodes.mesh_60_3.material} geometry={nodes.mesh_60_3.geometry} />
                <mesh material={nodes.mesh_60_4.material} geometry={nodes.mesh_60_4.geometry} />
                <mesh material={nodes.mesh_60_5.material} geometry={nodes.mesh_60_5.geometry} />
              </group>
              <group position={[-1, -0.25, 0]}>
                <group position={[-8, -15.25, -9.5]}>
                  <mesh material={nodes.mesh_61.material} geometry={nodes.mesh_61.geometry} />
                  <mesh material={nodes.mesh_61_1.material} geometry={nodes.mesh_61_1.geometry} />
                  <mesh material={nodes.mesh_61_2.material} geometry={nodes.mesh_61_2.geometry} />
                  <mesh material={nodes.mesh_61_3.material} geometry={nodes.mesh_61_3.geometry} />
                  <mesh material={nodes.mesh_61_4.material} geometry={nodes.mesh_61_4.geometry} />
                  <mesh material={nodes.mesh_61_5.material} geometry={nodes.mesh_61_5.geometry} />
                </group>
                <group position={[0.5, -14, 0]}>
                  <group position={[-8.5, -1.25, -9.5]}>
                    <mesh material={nodes.mesh_62.material} geometry={nodes.mesh_62.geometry} />
                    <mesh material={nodes.mesh_62_1.material} geometry={nodes.mesh_62_1.geometry} />
                    <mesh material={nodes.mesh_62_2.material} geometry={nodes.mesh_62_2.geometry} />
                    <mesh material={nodes.mesh_62_3.material} geometry={nodes.mesh_62_3.geometry} />
                    <mesh material={nodes.mesh_62_4.material} geometry={nodes.mesh_62_4.geometry} />
                    <mesh material={nodes.mesh_62_5.material} geometry={nodes.mesh_62_5.geometry} />
                  </group>
                  <group position={[0.5, 0, 0]}>
                    <group position={[-9, -1.25, -9.5]}>
                      <mesh material={nodes.mesh_63.material} geometry={nodes.mesh_63.geometry} />
                      <mesh material={nodes.mesh_63_1.material} geometry={nodes.mesh_63_1.geometry} />
                      <mesh material={nodes.mesh_63_2.material} geometry={nodes.mesh_63_2.geometry} />
                      <mesh material={nodes.mesh_63_3.material} geometry={nodes.mesh_63_3.geometry} />
                      <mesh material={nodes.mesh_63_4.material} geometry={nodes.mesh_63_4.geometry} />
                      <mesh material={nodes.mesh_63_5.material} geometry={nodes.mesh_63_5.geometry} />
                    </group>
                    <group position={[0, -18.25, 0]}>
                      <group position={[-9, 17, -9.5]}>
                        <mesh material={nodes.mesh_64.material} geometry={nodes.mesh_64.geometry} />
                        <mesh material={nodes.mesh_64_1.material} geometry={nodes.mesh_64_1.geometry} />
                        <mesh material={nodes.mesh_64_2.material} geometry={nodes.mesh_64_2.geometry} />
                        <mesh material={nodes.mesh_64_3.material} geometry={nodes.mesh_64_3.geometry} />
                        <mesh material={nodes.mesh_64_4.material} geometry={nodes.mesh_64_4.geometry} />
                        <mesh material={nodes.mesh_64_5.material} geometry={nodes.mesh_64_5.geometry} />
                      </group>
                      <group position={[-9, 17, -9.5]}>
                        <mesh material={nodes.mesh_65.material} geometry={nodes.mesh_65.geometry} />
                        <mesh material={nodes.mesh_65_1.material} geometry={nodes.mesh_65_1.geometry} />
                        <mesh material={nodes.mesh_65_2.material} geometry={nodes.mesh_65_2.geometry} />
                        <mesh material={nodes.mesh_65_3.material} geometry={nodes.mesh_65_3.geometry} />
                        <mesh material={nodes.mesh_65_4.material} geometry={nodes.mesh_65_4.geometry} />
                        <mesh material={nodes.mesh_65_5.material} geometry={nodes.mesh_65_5.geometry} />
                      </group>
                      <group position={[-9, 17, -9.5]}>
                        <mesh material={nodes.mesh_66.material} geometry={nodes.mesh_66.geometry} />
                        <mesh material={nodes.mesh_66_1.material} geometry={nodes.mesh_66_1.geometry} />
                        <mesh material={nodes.mesh_66_2.material} geometry={nodes.mesh_66_2.geometry} />
                        <mesh material={nodes.mesh_66_3.material} geometry={nodes.mesh_66_3.geometry} />
                        <mesh material={nodes.mesh_66_4.material} geometry={nodes.mesh_66_4.geometry} />
                        <mesh material={nodes.mesh_66_5.material} geometry={nodes.mesh_66_5.geometry} />
                      </group>
                      <group position={[-9, 17, -9.5]}>
                        <mesh material={nodes.mesh_67.material} geometry={nodes.mesh_67.geometry} />
                        <mesh material={nodes.mesh_67_1.material} geometry={nodes.mesh_67_1.geometry} />
                        <mesh material={nodes.mesh_67_2.material} geometry={nodes.mesh_67_2.geometry} />
                        <mesh material={nodes.mesh_67_3.material} geometry={nodes.mesh_67_3.geometry} />
                        <mesh material={nodes.mesh_67_4.material} geometry={nodes.mesh_67_4.geometry} />
                        <mesh material={nodes.mesh_67_5.material} geometry={nodes.mesh_67_5.geometry} />
                      </group>
                      <group position={[0, 3.25, -5]} rotation={[-Math.PI / 4, 0, 0]}>
                        <group position={[-9, 13.75, -4.5]}>
                          <mesh material={nodes.mesh_68.material} geometry={nodes.mesh_68.geometry} />
                          <mesh material={nodes.mesh_68_1.material} geometry={nodes.mesh_68_1.geometry} />
                          <mesh material={nodes.mesh_68_2.material} geometry={nodes.mesh_68_2.geometry} />
                          <mesh material={nodes.mesh_68_3.material} geometry={nodes.mesh_68_3.geometry} />
                          <mesh material={nodes.mesh_68_4.material} geometry={nodes.mesh_68_4.geometry} />
                          <mesh material={nodes.mesh_68_5.material} geometry={nodes.mesh_68_5.geometry} />
                        </group>
                      </group>
                      <group position={[0, 3.25, 5]} rotation={[-2.36, 0, 0]}>
                        <group position={[-9, 13.75, -14.5]}>
                          <mesh material={nodes.mesh_69.material} geometry={nodes.mesh_69.geometry} />
                          <mesh material={nodes.mesh_69_1.material} geometry={nodes.mesh_69_1.geometry} />
                          <mesh material={nodes.mesh_69_2.material} geometry={nodes.mesh_69_2.geometry} />
                          <mesh material={nodes.mesh_69_3.material} geometry={nodes.mesh_69_3.geometry} />
                          <mesh material={nodes.mesh_69_4.material} geometry={nodes.mesh_69_4.geometry} />
                          <mesh material={nodes.mesh_69_5.material} geometry={nodes.mesh_69_5.geometry} />
                        </group>
                      </group>
                      <group position={[-0.5, 1.75, 0]}>
                        <group position={[-8.5, 15.25, -9.5]}>
                          <mesh material={nodes.mesh_70.material} geometry={nodes.mesh_70.geometry} />
                          <mesh material={nodes.mesh_70_1.material} geometry={nodes.mesh_70_1.geometry} />
                          <mesh material={nodes.mesh_70_2.material} geometry={nodes.mesh_70_2.geometry} />
                          <mesh material={nodes.mesh_70_3.material} geometry={nodes.mesh_70_3.geometry} />
                          <mesh material={nodes.mesh_70_4.material} geometry={nodes.mesh_70_4.geometry} />
                          <mesh material={nodes.mesh_70_5.material} geometry={nodes.mesh_70_5.geometry} />
                        </group>
                        <group position={[-8.5, 15.25, -9.5]}>
                          <mesh material={nodes.mesh_71.material} geometry={nodes.mesh_71.geometry} />
                          <mesh material={nodes.mesh_71_1.material} geometry={nodes.mesh_71_1.geometry} />
                          <mesh material={nodes.mesh_71_2.material} geometry={nodes.mesh_71_2.geometry} />
                          <mesh material={nodes.mesh_71_3.material} geometry={nodes.mesh_71_3.geometry} />
                          <mesh material={nodes.mesh_71_4.material} geometry={nodes.mesh_71_4.geometry} />
                          <mesh material={nodes.mesh_71_5.material} geometry={nodes.mesh_71_5.geometry} />
                        </group>
                        <group position={[-8.5, 15.25, -9.5]}>
                          <mesh material={nodes.mesh_72.material} geometry={nodes.mesh_72.geometry} />
                          <mesh material={nodes.mesh_72_1.material} geometry={nodes.mesh_72_1.geometry} />
                          <mesh material={nodes.mesh_72_2.material} geometry={nodes.mesh_72_2.geometry} />
                          <mesh material={nodes.mesh_72_3.material} geometry={nodes.mesh_72_3.geometry} />
                          <mesh material={nodes.mesh_72_4.material} geometry={nodes.mesh_72_4.geometry} />
                          <mesh material={nodes.mesh_72_5.material} geometry={nodes.mesh_72_5.geometry} />
                        </group>
                        <group position={[-8.5, 15.25, -9.5]}>
                          <mesh material={nodes.mesh_73.material} geometry={nodes.mesh_73.geometry} />
                          <mesh material={nodes.mesh_73_1.material} geometry={nodes.mesh_73_1.geometry} />
                          <mesh material={nodes.mesh_73_2.material} geometry={nodes.mesh_73_2.geometry} />
                          <mesh material={nodes.mesh_73_3.material} geometry={nodes.mesh_73_3.geometry} />
                          <mesh material={nodes.mesh_73_4.material} geometry={nodes.mesh_73_4.geometry} />
                          <mesh material={nodes.mesh_73_5.material} geometry={nodes.mesh_73_5.geometry} />
                        </group>
                        <group position={[0.5, -3.25, -5]} rotation={[-0.17, 0, 0]}>
                          <group position={[-9, 18.5, -4.5]}>
                            <mesh material={nodes.mesh_74.material} geometry={nodes.mesh_74.geometry} />
                            <mesh material={nodes.mesh_74_1.material} geometry={nodes.mesh_74_1.geometry} />
                            <mesh material={nodes.mesh_74_2.material} geometry={nodes.mesh_74_2.geometry} />
                            <mesh material={nodes.mesh_74_3.material} geometry={nodes.mesh_74_3.geometry} />
                            <mesh material={nodes.mesh_74_4.material} geometry={nodes.mesh_74_4.geometry} />
                            <mesh material={nodes.mesh_74_5.material} geometry={nodes.mesh_74_5.geometry} />
                          </group>
                        </group>
                        <group position={[0.5, -3.25, 5]} rotation={[0.17, 0, 0]}>
                          <group position={[-9, 18.5, -14.5]}>
                            <mesh material={nodes.mesh_75.material} geometry={nodes.mesh_75.geometry} />
                            <mesh material={nodes.mesh_75_1.material} geometry={nodes.mesh_75_1.geometry} />
                            <mesh material={nodes.mesh_75_2.material} geometry={nodes.mesh_75_2.geometry} />
                            <mesh material={nodes.mesh_75_3.material} geometry={nodes.mesh_75_3.geometry} />
                            <mesh material={nodes.mesh_75_4.material} geometry={nodes.mesh_75_4.geometry} />
                            <mesh material={nodes.mesh_75_5.material} geometry={nodes.mesh_75_5.geometry} />
                          </group>
                        </group>
                        <group position={[5.5, -3.25, 0]} rotation={[Math.PI / 2, 1.4, -Math.PI / 2]}>
                          <group position={[-14, 18.5, -9.5]}>
                            <mesh material={nodes.mesh_76.material} geometry={nodes.mesh_76.geometry} />
                            <mesh material={nodes.mesh_76_1.material} geometry={nodes.mesh_76_1.geometry} />
                            <mesh material={nodes.mesh_76_2.material} geometry={nodes.mesh_76_2.geometry} />
                            <mesh material={nodes.mesh_76_3.material} geometry={nodes.mesh_76_3.geometry} />
                            <mesh material={nodes.mesh_76_4.material} geometry={nodes.mesh_76_4.geometry} />
                            <mesh material={nodes.mesh_76_5.material} geometry={nodes.mesh_76_5.geometry} />
                          </group>
                        </group>
                        <group position={[-4.5, -3.25, 0]} rotation={[-Math.PI / 2, 1.4, Math.PI / 2]}>
                          <group position={[-4, 18.5, -9.5]}>
                            <mesh material={nodes.mesh_77.material} geometry={nodes.mesh_77.geometry} />
                            <mesh material={nodes.mesh_77_1.material} geometry={nodes.mesh_77_1.geometry} />
                            <mesh material={nodes.mesh_77_2.material} geometry={nodes.mesh_77_2.geometry} />
                            <mesh material={nodes.mesh_77_3.material} geometry={nodes.mesh_77_3.geometry} />
                            <mesh material={nodes.mesh_77_4.material} geometry={nodes.mesh_77_4.geometry} />
                            <mesh material={nodes.mesh_77_5.material} geometry={nodes.mesh_77_5.geometry} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group position={[-5.5, 9.75, -14]}>
          <group position={[-3.5, 0.25, -8]}>
            <group position={[-1, -0.25, 0]}>
              <group position={[0.5, -14, 0]}>
                <group position={[0.5, 0, 0]}>
                  <group position={[0, -18.25, 0]}>
                    <group position={[0, 3.25, -5]} rotation={[-Math.PI / 4, 0, 0]}>
                      <group position={[9, 13.75, 23.5]}>
                        <mesh material={nodes.mesh_87.material} geometry={nodes.mesh_87.geometry} />
                        <mesh material={nodes.mesh_87_1.material} geometry={nodes.mesh_87_1.geometry} />
                        <mesh material={nodes.mesh_87_2.material} geometry={nodes.mesh_87_2.geometry} />
                        <mesh material={nodes.mesh_87_3.material} geometry={nodes.mesh_87_3.geometry} />
                        <mesh material={nodes.mesh_87_4.material} geometry={nodes.mesh_87_4.geometry} />
                        <mesh material={nodes.mesh_87_5.material} geometry={nodes.mesh_87_5.geometry} />
                      </group>
                    </group>
                    <group position={[0, 3.25, 5]} rotation={[-2.36, 0, 0]}>
                      <group position={[9, 13.75, 13.5]}>
                        <mesh material={nodes.mesh_88.material} geometry={nodes.mesh_88.geometry} />
                        <mesh material={nodes.mesh_88_1.material} geometry={nodes.mesh_88_1.geometry} />
                        <mesh material={nodes.mesh_88_2.material} geometry={nodes.mesh_88_2.geometry} />
                        <mesh material={nodes.mesh_88_3.material} geometry={nodes.mesh_88_3.geometry} />
                        <mesh material={nodes.mesh_88_4.material} geometry={nodes.mesh_88_4.geometry} />
                        <mesh material={nodes.mesh_88_5.material} geometry={nodes.mesh_88_5.geometry} />
                      </group>
                    </group>
                    <group position={[-0.5, 1.75, 0]}>
                      <group position={[0.5, -3.25, -5]} rotation={[-0.17, 0, 0]}>
                        <group position={[9, 18.5, 23.5]}>
                          <mesh material={nodes.mesh_93.material} geometry={nodes.mesh_93.geometry} />
                          <mesh material={nodes.mesh_93_1.material} geometry={nodes.mesh_93_1.geometry} />
                          <mesh material={nodes.mesh_93_2.material} geometry={nodes.mesh_93_2.geometry} />
                          <mesh material={nodes.mesh_93_3.material} geometry={nodes.mesh_93_3.geometry} />
                          <mesh material={nodes.mesh_93_4.material} geometry={nodes.mesh_93_4.geometry} />
                          <mesh material={nodes.mesh_93_5.material} geometry={nodes.mesh_93_5.geometry} />
                        </group>
                      </group>
                      <group position={[0.5, -3.25, 5]} rotation={[0.17, 0, 0]}>
                        <group position={[9, 18.5, 13.5]}>
                          <mesh material={nodes.mesh_94.material} geometry={nodes.mesh_94.geometry} />
                          <mesh material={nodes.mesh_94_1.material} geometry={nodes.mesh_94_1.geometry} />
                          <mesh material={nodes.mesh_94_2.material} geometry={nodes.mesh_94_2.geometry} />
                          <mesh material={nodes.mesh_94_3.material} geometry={nodes.mesh_94_3.geometry} />
                          <mesh material={nodes.mesh_94_4.material} geometry={nodes.mesh_94_4.geometry} />
                          <mesh material={nodes.mesh_94_5.material} geometry={nodes.mesh_94_5.geometry} />
                        </group>
                      </group>
                      <group position={[5.5, -3.25, 0]} rotation={[Math.PI / 2, 1.4, -Math.PI / 2]}>
                        <group position={[4, 18.5, 18.5]}>
                          <mesh material={nodes.mesh_95.material} geometry={nodes.mesh_95.geometry} />
                          <mesh material={nodes.mesh_95_1.material} geometry={nodes.mesh_95_1.geometry} />
                          <mesh material={nodes.mesh_95_2.material} geometry={nodes.mesh_95_2.geometry} />
                          <mesh material={nodes.mesh_95_3.material} geometry={nodes.mesh_95_3.geometry} />
                          <mesh material={nodes.mesh_95_4.material} geometry={nodes.mesh_95_4.geometry} />
                          <mesh material={nodes.mesh_95_5.material} geometry={nodes.mesh_95_5.geometry} />
                        </group>
                      </group>
                      <group position={[-4.5, -3.25, 0]} rotation={[-Math.PI / 2, 1.4, Math.PI / 2]}>
                        <group position={[14, 18.5, 18.5]}>
                          <mesh material={nodes.mesh_96.material} geometry={nodes.mesh_96.geometry} />
                          <mesh material={nodes.mesh_96_1.material} geometry={nodes.mesh_96_1.geometry} />
                          <mesh material={nodes.mesh_96_2.material} geometry={nodes.mesh_96_2.geometry} />
                          <mesh material={nodes.mesh_96_3.material} geometry={nodes.mesh_96_3.geometry} />
                          <mesh material={nodes.mesh_96_4.material} geometry={nodes.mesh_96_4.geometry} />
                          <mesh material={nodes.mesh_96_5.material} geometry={nodes.mesh_96_5.geometry} />
                        </group>
                      </group>
                      <group position={[9.5, 15.25, 18.5]}>
                        <mesh material={nodes.mesh_89.material} geometry={nodes.mesh_89.geometry} />
                        <mesh material={nodes.mesh_89_1.material} geometry={nodes.mesh_89_1.geometry} />
                        <mesh material={nodes.mesh_89_2.material} geometry={nodes.mesh_89_2.geometry} />
                        <mesh material={nodes.mesh_89_3.material} geometry={nodes.mesh_89_3.geometry} />
                        <mesh material={nodes.mesh_89_4.material} geometry={nodes.mesh_89_4.geometry} />
                        <mesh material={nodes.mesh_89_5.material} geometry={nodes.mesh_89_5.geometry} />
                      </group>
                      <group position={[9.5, 15.25, 18.5]}>
                        <mesh material={nodes.mesh_90.material} geometry={nodes.mesh_90.geometry} />
                        <mesh material={nodes.mesh_90_1.material} geometry={nodes.mesh_90_1.geometry} />
                        <mesh material={nodes.mesh_90_2.material} geometry={nodes.mesh_90_2.geometry} />
                        <mesh material={nodes.mesh_90_3.material} geometry={nodes.mesh_90_3.geometry} />
                        <mesh material={nodes.mesh_90_4.material} geometry={nodes.mesh_90_4.geometry} />
                        <mesh material={nodes.mesh_90_5.material} geometry={nodes.mesh_90_5.geometry} />
                      </group>
                      <group position={[9.5, 15.25, 18.5]}>
                        <mesh material={nodes.mesh_91.material} geometry={nodes.mesh_91.geometry} />
                        <mesh material={nodes.mesh_91_1.material} geometry={nodes.mesh_91_1.geometry} />
                        <mesh material={nodes.mesh_91_2.material} geometry={nodes.mesh_91_2.geometry} />
                        <mesh material={nodes.mesh_91_3.material} geometry={nodes.mesh_91_3.geometry} />
                        <mesh material={nodes.mesh_91_4.material} geometry={nodes.mesh_91_4.geometry} />
                        <mesh material={nodes.mesh_91_5.material} geometry={nodes.mesh_91_5.geometry} />
                      </group>
                      <group position={[9.5, 15.25, 18.5]}>
                        <mesh material={nodes.mesh_92.material} geometry={nodes.mesh_92.geometry} />
                        <mesh material={nodes.mesh_92_1.material} geometry={nodes.mesh_92_1.geometry} />
                        <mesh material={nodes.mesh_92_2.material} geometry={nodes.mesh_92_2.geometry} />
                        <mesh material={nodes.mesh_92_3.material} geometry={nodes.mesh_92_3.geometry} />
                        <mesh material={nodes.mesh_92_4.material} geometry={nodes.mesh_92_4.geometry} />
                        <mesh material={nodes.mesh_92_5.material} geometry={nodes.mesh_92_5.geometry} />
                      </group>
                    </group>
                    <group position={[9, 17, 18.5]}>
                      <mesh material={nodes.mesh_83.material} geometry={nodes.mesh_83.geometry} />
                      <mesh material={nodes.mesh_83_1.material} geometry={nodes.mesh_83_1.geometry} />
                      <mesh material={nodes.mesh_83_2.material} geometry={nodes.mesh_83_2.geometry} />
                      <mesh material={nodes.mesh_83_3.material} geometry={nodes.mesh_83_3.geometry} />
                      <mesh material={nodes.mesh_83_4.material} geometry={nodes.mesh_83_4.geometry} />
                      <mesh material={nodes.mesh_83_5.material} geometry={nodes.mesh_83_5.geometry} />
                    </group>
                    <group position={[9, 17, 18.5]}>
                      <mesh material={nodes.mesh_84.material} geometry={nodes.mesh_84.geometry} />
                      <mesh material={nodes.mesh_84_1.material} geometry={nodes.mesh_84_1.geometry} />
                      <mesh material={nodes.mesh_84_2.material} geometry={nodes.mesh_84_2.geometry} />
                      <mesh material={nodes.mesh_84_3.material} geometry={nodes.mesh_84_3.geometry} />
                      <mesh material={nodes.mesh_84_4.material} geometry={nodes.mesh_84_4.geometry} />
                      <mesh material={nodes.mesh_84_5.material} geometry={nodes.mesh_84_5.geometry} />
                    </group>
                    <group position={[9, 17, 18.5]}>
                      <mesh material={nodes.mesh_85.material} geometry={nodes.mesh_85.geometry} />
                      <mesh material={nodes.mesh_85_1.material} geometry={nodes.mesh_85_1.geometry} />
                      <mesh material={nodes.mesh_85_2.material} geometry={nodes.mesh_85_2.geometry} />
                      <mesh material={nodes.mesh_85_3.material} geometry={nodes.mesh_85_3.geometry} />
                      <mesh material={nodes.mesh_85_4.material} geometry={nodes.mesh_85_4.geometry} />
                      <mesh material={nodes.mesh_85_5.material} geometry={nodes.mesh_85_5.geometry} />
                    </group>
                    <group position={[9, 17, 18.5]}>
                      <mesh material={nodes.mesh_86.material} geometry={nodes.mesh_86.geometry} />
                      <mesh material={nodes.mesh_86_1.material} geometry={nodes.mesh_86_1.geometry} />
                      <mesh material={nodes.mesh_86_2.material} geometry={nodes.mesh_86_2.geometry} />
                      <mesh material={nodes.mesh_86_3.material} geometry={nodes.mesh_86_3.geometry} />
                      <mesh material={nodes.mesh_86_4.material} geometry={nodes.mesh_86_4.geometry} />
                      <mesh material={nodes.mesh_86_5.material} geometry={nodes.mesh_86_5.geometry} />
                    </group>
                  </group>
                  <group position={[9, -1.25, 18.5]}>
                    <mesh material={nodes.mesh_82.material} geometry={nodes.mesh_82.geometry} />
                    <mesh material={nodes.mesh_82_1.material} geometry={nodes.mesh_82_1.geometry} />
                    <mesh material={nodes.mesh_82_2.material} geometry={nodes.mesh_82_2.geometry} />
                    <mesh material={nodes.mesh_82_3.material} geometry={nodes.mesh_82_3.geometry} />
                    <mesh material={nodes.mesh_82_4.material} geometry={nodes.mesh_82_4.geometry} />
                    <mesh material={nodes.mesh_82_5.material} geometry={nodes.mesh_82_5.geometry} />
                  </group>
                </group>
                <group position={[9.5, -1.25, 18.5]}>
                  <mesh material={nodes.mesh_81.material} geometry={nodes.mesh_81.geometry} />
                  <mesh material={nodes.mesh_81_1.material} geometry={nodes.mesh_81_1.geometry} />
                  <mesh material={nodes.mesh_81_2.material} geometry={nodes.mesh_81_2.geometry} />
                  <mesh material={nodes.mesh_81_3.material} geometry={nodes.mesh_81_3.geometry} />
                  <mesh material={nodes.mesh_81_4.material} geometry={nodes.mesh_81_4.geometry} />
                  <mesh material={nodes.mesh_81_5.material} geometry={nodes.mesh_81_5.geometry} />
                </group>
              </group>
              <group position={[10, -15.25, 18.5]}>
                <mesh material={nodes.mesh_80.material} geometry={nodes.mesh_80.geometry} />
                <mesh material={nodes.mesh_80_1.material} geometry={nodes.mesh_80_1.geometry} />
                <mesh material={nodes.mesh_80_2.material} geometry={nodes.mesh_80_2.geometry} />
                <mesh material={nodes.mesh_80_3.material} geometry={nodes.mesh_80_3.geometry} />
                <mesh material={nodes.mesh_80_4.material} geometry={nodes.mesh_80_4.geometry} />
                <mesh material={nodes.mesh_80_5.material} geometry={nodes.mesh_80_5.geometry} />
              </group>
            </group>
            <group position={[9, -15.5, 18.5]}>
              <mesh material={nodes.mesh_79.material} geometry={nodes.mesh_79.geometry} />
              <mesh material={nodes.mesh_79_1.material} geometry={nodes.mesh_79_1.geometry} />
              <mesh material={nodes.mesh_79_2.material} geometry={nodes.mesh_79_2.geometry} />
              <mesh material={nodes.mesh_79_3.material} geometry={nodes.mesh_79_3.geometry} />
              <mesh material={nodes.mesh_79_4.material} geometry={nodes.mesh_79_4.geometry} />
              <mesh material={nodes.mesh_79_5.material} geometry={nodes.mesh_79_5.geometry} />
            </group>
          </group>
          <group position={[5.5, -15.25, 10.5]}>
            <mesh material={nodes.mesh_78.material} geometry={nodes.mesh_78.geometry} />
            <mesh material={nodes.mesh_78_1.material} geometry={nodes.mesh_78_1.geometry} />
            <mesh material={nodes.mesh_78_2.material} geometry={nodes.mesh_78_2.geometry} />
            <mesh material={nodes.mesh_78_3.material} geometry={nodes.mesh_78_3.geometry} />
            <mesh material={nodes.mesh_78_4.material} geometry={nodes.mesh_78_4.geometry} />
            <mesh material={nodes.mesh_78_5.material} geometry={nodes.mesh_78_5.geometry} />
          </group>
        </group>
        <group position={[-5.5, 9.75, -2]}>
          <group position={[-3.5, 0.25, 8]}>
            <group position={[-1, -0.25, 0]}>
              <group position={[0.5, -14, 0]}>
                <group position={[0.5, 0, 0]}>
                  <group position={[0, -18.25, 0]}>
                    <group position={[0, 3.25, -5]} rotation={[-Math.PI / 4, 0, 0]}>
                      <group position={[9, 13.75, -4.5]}>
                        <mesh material={nodes.mesh_106.material} geometry={nodes.mesh_106.geometry} />
                        <mesh material={nodes.mesh_106_1.material} geometry={nodes.mesh_106_1.geometry} />
                        <mesh material={nodes.mesh_106_2.material} geometry={nodes.mesh_106_2.geometry} />
                        <mesh material={nodes.mesh_106_3.material} geometry={nodes.mesh_106_3.geometry} />
                        <mesh material={nodes.mesh_106_4.material} geometry={nodes.mesh_106_4.geometry} />
                        <mesh material={nodes.mesh_106_5.material} geometry={nodes.mesh_106_5.geometry} />
                      </group>
                    </group>
                    <group position={[0, 3.25, 5]} rotation={[-2.36, 0, 0]}>
                      <group position={[9, 13.75, -14.5]}>
                        <mesh material={nodes.mesh_107.material} geometry={nodes.mesh_107.geometry} />
                        <mesh material={nodes.mesh_107_1.material} geometry={nodes.mesh_107_1.geometry} />
                        <mesh material={nodes.mesh_107_2.material} geometry={nodes.mesh_107_2.geometry} />
                        <mesh material={nodes.mesh_107_3.material} geometry={nodes.mesh_107_3.geometry} />
                        <mesh material={nodes.mesh_107_4.material} geometry={nodes.mesh_107_4.geometry} />
                        <mesh material={nodes.mesh_107_5.material} geometry={nodes.mesh_107_5.geometry} />
                      </group>
                    </group>
                    <group position={[-0.5, 1.75, 0]}>
                      <group position={[0.5, -3.25, -5]} rotation={[-0.17, 0, 0]}>
                        <group position={[9, 18.5, -4.5]}>
                          <mesh material={nodes.mesh_112.material} geometry={nodes.mesh_112.geometry} />
                          <mesh material={nodes.mesh_112_1.material} geometry={nodes.mesh_112_1.geometry} />
                          <mesh material={nodes.mesh_112_2.material} geometry={nodes.mesh_112_2.geometry} />
                          <mesh material={nodes.mesh_112_3.material} geometry={nodes.mesh_112_3.geometry} />
                          <mesh material={nodes.mesh_112_4.material} geometry={nodes.mesh_112_4.geometry} />
                          <mesh material={nodes.mesh_112_5.material} geometry={nodes.mesh_112_5.geometry} />
                        </group>
                      </group>
                      <group position={[0.5, -3.25, 5]} rotation={[0.17, 0, 0]}>
                        <group position={[9, 18.5, -14.5]}>
                          <mesh material={nodes.mesh_113.material} geometry={nodes.mesh_113.geometry} />
                          <mesh material={nodes.mesh_113_1.material} geometry={nodes.mesh_113_1.geometry} />
                          <mesh material={nodes.mesh_113_2.material} geometry={nodes.mesh_113_2.geometry} />
                          <mesh material={nodes.mesh_113_3.material} geometry={nodes.mesh_113_3.geometry} />
                          <mesh material={nodes.mesh_113_4.material} geometry={nodes.mesh_113_4.geometry} />
                          <mesh material={nodes.mesh_113_5.material} geometry={nodes.mesh_113_5.geometry} />
                        </group>
                      </group>
                      <group position={[5.5, -3.25, 0]} rotation={[Math.PI / 2, 1.4, -Math.PI / 2]}>
                        <group position={[4, 18.5, -9.5]}>
                          <mesh material={nodes.mesh_114.material} geometry={nodes.mesh_114.geometry} />
                          <mesh material={nodes.mesh_114_1.material} geometry={nodes.mesh_114_1.geometry} />
                          <mesh material={nodes.mesh_114_2.material} geometry={nodes.mesh_114_2.geometry} />
                          <mesh material={nodes.mesh_114_3.material} geometry={nodes.mesh_114_3.geometry} />
                          <mesh material={nodes.mesh_114_4.material} geometry={nodes.mesh_114_4.geometry} />
                          <mesh material={nodes.mesh_114_5.material} geometry={nodes.mesh_114_5.geometry} />
                        </group>
                      </group>
                      <group position={[-4.5, -3.25, 0]} rotation={[-Math.PI / 2, 1.4, Math.PI / 2]}>
                        <group position={[14, 18.5, -9.5]}>
                          <mesh material={nodes.mesh_115.material} geometry={nodes.mesh_115.geometry} />
                          <mesh material={nodes.mesh_115_1.material} geometry={nodes.mesh_115_1.geometry} />
                          <mesh material={nodes.mesh_115_2.material} geometry={nodes.mesh_115_2.geometry} />
                          <mesh material={nodes.mesh_115_3.material} geometry={nodes.mesh_115_3.geometry} />
                          <mesh material={nodes.mesh_115_4.material} geometry={nodes.mesh_115_4.geometry} />
                          <mesh material={nodes.mesh_115_5.material} geometry={nodes.mesh_115_5.geometry} />
                        </group>
                      </group>
                      <group position={[9.5, 15.25, -9.5]}>
                        <mesh material={nodes.mesh_108.material} geometry={nodes.mesh_108.geometry} />
                        <mesh material={nodes.mesh_108_1.material} geometry={nodes.mesh_108_1.geometry} />
                        <mesh material={nodes.mesh_108_2.material} geometry={nodes.mesh_108_2.geometry} />
                        <mesh material={nodes.mesh_108_3.material} geometry={nodes.mesh_108_3.geometry} />
                        <mesh material={nodes.mesh_108_4.material} geometry={nodes.mesh_108_4.geometry} />
                        <mesh material={nodes.mesh_108_5.material} geometry={nodes.mesh_108_5.geometry} />
                      </group>
                      <group position={[9.5, 15.25, -9.5]}>
                        <mesh material={nodes.mesh_109.material} geometry={nodes.mesh_109.geometry} />
                        <mesh material={nodes.mesh_109_1.material} geometry={nodes.mesh_109_1.geometry} />
                        <mesh material={nodes.mesh_109_2.material} geometry={nodes.mesh_109_2.geometry} />
                        <mesh material={nodes.mesh_109_3.material} geometry={nodes.mesh_109_3.geometry} />
                        <mesh material={nodes.mesh_109_4.material} geometry={nodes.mesh_109_4.geometry} />
                        <mesh material={nodes.mesh_109_5.material} geometry={nodes.mesh_109_5.geometry} />
                      </group>
                      <group position={[9.5, 15.25, -9.5]}>
                        <mesh material={nodes.mesh_110.material} geometry={nodes.mesh_110.geometry} />
                        <mesh material={nodes.mesh_110_1.material} geometry={nodes.mesh_110_1.geometry} />
                        <mesh material={nodes.mesh_110_2.material} geometry={nodes.mesh_110_2.geometry} />
                        <mesh material={nodes.mesh_110_3.material} geometry={nodes.mesh_110_3.geometry} />
                        <mesh material={nodes.mesh_110_4.material} geometry={nodes.mesh_110_4.geometry} />
                        <mesh material={nodes.mesh_110_5.material} geometry={nodes.mesh_110_5.geometry} />
                      </group>
                      <group position={[9.5, 15.25, -9.5]}>
                        <mesh material={nodes.mesh_111.material} geometry={nodes.mesh_111.geometry} />
                        <mesh material={nodes.mesh_111_1.material} geometry={nodes.mesh_111_1.geometry} />
                        <mesh material={nodes.mesh_111_2.material} geometry={nodes.mesh_111_2.geometry} />
                        <mesh material={nodes.mesh_111_3.material} geometry={nodes.mesh_111_3.geometry} />
                        <mesh material={nodes.mesh_111_4.material} geometry={nodes.mesh_111_4.geometry} />
                        <mesh material={nodes.mesh_111_5.material} geometry={nodes.mesh_111_5.geometry} />
                      </group>
                    </group>
                    <group position={[9, 17, -9.5]}>
                      <mesh material={nodes.mesh_102.material} geometry={nodes.mesh_102.geometry} />
                      <mesh material={nodes.mesh_102_1.material} geometry={nodes.mesh_102_1.geometry} />
                      <mesh material={nodes.mesh_102_2.material} geometry={nodes.mesh_102_2.geometry} />
                      <mesh material={nodes.mesh_102_3.material} geometry={nodes.mesh_102_3.geometry} />
                      <mesh material={nodes.mesh_102_4.material} geometry={nodes.mesh_102_4.geometry} />
                      <mesh material={nodes.mesh_102_5.material} geometry={nodes.mesh_102_5.geometry} />
                    </group>
                    <group position={[9, 17, -9.5]}>
                      <mesh material={nodes.mesh_103.material} geometry={nodes.mesh_103.geometry} />
                      <mesh material={nodes.mesh_103_1.material} geometry={nodes.mesh_103_1.geometry} />
                      <mesh material={nodes.mesh_103_2.material} geometry={nodes.mesh_103_2.geometry} />
                      <mesh material={nodes.mesh_103_3.material} geometry={nodes.mesh_103_3.geometry} />
                      <mesh material={nodes.mesh_103_4.material} geometry={nodes.mesh_103_4.geometry} />
                      <mesh material={nodes.mesh_103_5.material} geometry={nodes.mesh_103_5.geometry} />
                    </group>
                    <group position={[9, 17, -9.5]}>
                      <mesh material={nodes.mesh_104.material} geometry={nodes.mesh_104.geometry} />
                      <mesh material={nodes.mesh_104_1.material} geometry={nodes.mesh_104_1.geometry} />
                      <mesh material={nodes.mesh_104_2.material} geometry={nodes.mesh_104_2.geometry} />
                      <mesh material={nodes.mesh_104_3.material} geometry={nodes.mesh_104_3.geometry} />
                      <mesh material={nodes.mesh_104_4.material} geometry={nodes.mesh_104_4.geometry} />
                      <mesh material={nodes.mesh_104_5.material} geometry={nodes.mesh_104_5.geometry} />
                    </group>
                    <group position={[9, 17, -9.5]}>
                      <mesh material={nodes.mesh_105.material} geometry={nodes.mesh_105.geometry} />
                      <mesh material={nodes.mesh_105_1.material} geometry={nodes.mesh_105_1.geometry} />
                      <mesh material={nodes.mesh_105_2.material} geometry={nodes.mesh_105_2.geometry} />
                      <mesh material={nodes.mesh_105_3.material} geometry={nodes.mesh_105_3.geometry} />
                      <mesh material={nodes.mesh_105_4.material} geometry={nodes.mesh_105_4.geometry} />
                      <mesh material={nodes.mesh_105_5.material} geometry={nodes.mesh_105_5.geometry} />
                    </group>
                  </group>
                  <group position={[9, -1.25, -9.5]}>
                    <mesh material={nodes.mesh_101.material} geometry={nodes.mesh_101.geometry} />
                    <mesh material={nodes.mesh_101_1.material} geometry={nodes.mesh_101_1.geometry} />
                    <mesh material={nodes.mesh_101_2.material} geometry={nodes.mesh_101_2.geometry} />
                    <mesh material={nodes.mesh_101_3.material} geometry={nodes.mesh_101_3.geometry} />
                    <mesh material={nodes.mesh_101_4.material} geometry={nodes.mesh_101_4.geometry} />
                    <mesh material={nodes.mesh_101_5.material} geometry={nodes.mesh_101_5.geometry} />
                  </group>
                </group>
                <group position={[9.5, -1.25, -9.5]}>
                  <mesh material={nodes.mesh_100.material} geometry={nodes.mesh_100.geometry} />
                  <mesh material={nodes.mesh_100_1.material} geometry={nodes.mesh_100_1.geometry} />
                  <mesh material={nodes.mesh_100_2.material} geometry={nodes.mesh_100_2.geometry} />
                  <mesh material={nodes.mesh_100_3.material} geometry={nodes.mesh_100_3.geometry} />
                  <mesh material={nodes.mesh_100_4.material} geometry={nodes.mesh_100_4.geometry} />
                  <mesh material={nodes.mesh_100_5.material} geometry={nodes.mesh_100_5.geometry} />
                </group>
              </group>
              <group position={[10, -15.25, -9.5]}>
                <mesh material={nodes.mesh_99.material} geometry={nodes.mesh_99.geometry} />
                <mesh material={nodes.mesh_99_1.material} geometry={nodes.mesh_99_1.geometry} />
                <mesh material={nodes.mesh_99_2.material} geometry={nodes.mesh_99_2.geometry} />
                <mesh material={nodes.mesh_99_3.material} geometry={nodes.mesh_99_3.geometry} />
                <mesh material={nodes.mesh_99_4.material} geometry={nodes.mesh_99_4.geometry} />
                <mesh material={nodes.mesh_99_5.material} geometry={nodes.mesh_99_5.geometry} />
              </group>
            </group>
            <group position={[9, -15.5, -9.5]}>
              <mesh material={nodes.mesh_98.material} geometry={nodes.mesh_98.geometry} />
              <mesh material={nodes.mesh_98_1.material} geometry={nodes.mesh_98_1.geometry} />
              <mesh material={nodes.mesh_98_2.material} geometry={nodes.mesh_98_2.geometry} />
              <mesh material={nodes.mesh_98_3.material} geometry={nodes.mesh_98_3.geometry} />
              <mesh material={nodes.mesh_98_4.material} geometry={nodes.mesh_98_4.geometry} />
              <mesh material={nodes.mesh_98_5.material} geometry={nodes.mesh_98_5.geometry} />
            </group>
          </group>
          <group position={[5.5, -15.25, -1.5]}>
            <mesh material={nodes.mesh_97.material} geometry={nodes.mesh_97.geometry} />
            <mesh material={nodes.mesh_97_1.material} geometry={nodes.mesh_97_1.geometry} />
            <mesh material={nodes.mesh_97_2.material} geometry={nodes.mesh_97_2.geometry} />
            <mesh material={nodes.mesh_97_3.material} geometry={nodes.mesh_97_3.geometry} />
            <mesh material={nodes.mesh_97_4.material} geometry={nodes.mesh_97_4.geometry} />
            <mesh material={nodes.mesh_97_5.material} geometry={nodes.mesh_97_5.geometry} />
          </group>
        </group>
        <group position={[0, -5.5, -3.5]}>
          <mesh material={nodes.mesh_0.material} geometry={nodes.mesh_0.geometry} />
          <mesh material={nodes.mesh_0_1.material} geometry={nodes.mesh_0_1.geometry} />
          <mesh material={nodes.mesh_0_2.material} geometry={nodes.mesh_0_2.geometry} />
          <mesh material={nodes.mesh_0_3.material} geometry={nodes.mesh_0_3.geometry} />
          <mesh material={nodes.mesh_0_4.material} geometry={nodes.mesh_0_4.geometry} />
          <mesh material={nodes.mesh_0_5.material} geometry={nodes.mesh_0_5.geometry} />
        </group>
        <group position={[0, -5.5, -3.5]}>
          <mesh material={nodes.mesh_1.material} geometry={nodes.mesh_1.geometry} />
          <mesh material={nodes.mesh_1_1.material} geometry={nodes.mesh_1_1.geometry} />
          <mesh material={nodes.mesh_1_2.material} geometry={nodes.mesh_1_2.geometry} />
          <mesh material={nodes.mesh_1_3.material} geometry={nodes.mesh_1_3.geometry} />
          <mesh material={nodes.mesh_1_4.material} geometry={nodes.mesh_1_4.geometry} />
          <mesh material={nodes.mesh_1_5.material} geometry={nodes.mesh_1_5.geometry} />
        </group>
        <group position={[0, -5.5, -3.5]}>
          <mesh material={nodes.mesh_2.material} geometry={nodes.mesh_2.geometry} />
          <mesh material={nodes.mesh_2_1.material} geometry={nodes.mesh_2_1.geometry} />
          <mesh material={nodes.mesh_2_2.material} geometry={nodes.mesh_2_2.geometry} />
          <mesh material={nodes.mesh_2_3.material} geometry={nodes.mesh_2_3.geometry} />
          <mesh material={nodes.mesh_2_4.material} geometry={nodes.mesh_2_4.geometry} />
          <mesh material={nodes.mesh_2_5.material} geometry={nodes.mesh_2_5.geometry} />
        </group>
        <group position={[0, -5.5, -3.5]}>
          <mesh material={nodes.mesh_3.material} geometry={nodes.mesh_3.geometry} />
          <mesh material={nodes.mesh_3_1.material} geometry={nodes.mesh_3_1.geometry} />
          <mesh material={nodes.mesh_3_2.material} geometry={nodes.mesh_3_2.geometry} />
          <mesh material={nodes.mesh_3_3.material} geometry={nodes.mesh_3_3.geometry} />
          <mesh material={nodes.mesh_3_4.material} geometry={nodes.mesh_3_4.geometry} />
          <mesh material={nodes.mesh_3_5.material} geometry={nodes.mesh_3_5.geometry} />
        </group>
        <group position={[0, -5.5, -3.5]}>
          <mesh material={nodes.mesh_4.material} geometry={nodes.mesh_4.geometry} />
          <mesh material={nodes.mesh_4_1.material} geometry={nodes.mesh_4_1.geometry} />
          <mesh material={nodes.mesh_4_2.material} geometry={nodes.mesh_4_2.geometry} />
          <mesh material={nodes.mesh_4_3.material} geometry={nodes.mesh_4_3.geometry} />
          <mesh material={nodes.mesh_4_4.material} geometry={nodes.mesh_4_4.geometry} />
          <mesh material={nodes.mesh_4_5.material} geometry={nodes.mesh_4_5.geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/source/model.gltf')
