/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useFrame } from 'react-three-fiber'
import { useGLTF } from '@react-three/drei/useGLTF'

import { useAnimations } from '@react-three/drei/useAnimations'

export default function Mutant(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('../../../models/mutant/newmutant.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    actions.mutant.play();
  })
  return (
    <group ref={group} {...props} dispose={null} position={[0,-.8,0]}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <primitive object={nodes.MutantHips} />
        <skinnedMesh
          /* x */
          material={materials['mutant_M.001']}
          geometry={nodes.MutantMesh.geometry}
          skeleton={nodes.MutantMesh.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/mutant/newmutant.glb')
