/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useFrame } from 'react-three-fiber'
import { useGLTF } from '@react-three/drei/useGLTF'

import { useAnimations } from '@react-three/drei/useAnimations'

export default function Soldier(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('../../../models/soldier/soldier.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    console.log(actions)
    actions.soldier.play();
  })
  return (
    <group ref={group} {...props} dispose={null} position={[0,-1,0]}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          material={materials.VanguardBodyMat}
          geometry={nodes.vanguard_Mesh.geometry}
          skeleton={nodes.vanguard_Mesh.skeleton}
        />
        <skinnedMesh
          material={materials.Vanguard_VisorMat}
          geometry={nodes.vanguard_visor.geometry}
          skeleton={nodes.vanguard_visor.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/soldier/soldier.glb')
